version: '3.9'

services:
  db:
    container_name: "db"
    image: postgres:15.0-alpine
    volumes:
      - db_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=blog_backend
    env_file:
      - ./src/blog/.env
    ports:
      - "5432:5432"
    restart: always

  blog_backend:
    container_name: "blog_backend"
    build: .
    restart: always
    volumes:
      - static_value:/app/src/static/
    depends_on:
      - db
    env_file:
      - ./src/blog/.env
    command: >
      sh -c "cd ./src &&
             python manage.py collectstatic --no-input &&
             python manage.py migrate &&
             gunicorn blog.wsgi:application --bind 0:8000"

  nginx:
    container_name: "nginx"
    image: nginx:1.25.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static
    depends_on:
      - blog_backend

volumes:
  db_volume:
  static_value:
