# Generated by Django 4.2.9 on 2024-02-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': ('Подписка',), 'verbose_name_plural': 'Подписки'},
        ),
    ]
