# Generated by Django 4.2.9 on 2024-02-06 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок поста', max_length=50, verbose_name='Заголовок')),
                ('text', models.TextField(help_text='Напишите содержимое поста', max_length=140, verbose_name='Текст поста')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания поста')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор поста')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='IsRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_read', to='posts.post', verbose_name='Пост прочитан/не прочитан')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_read', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статус поста "Прочитан"',
                'verbose_name_plural': 'Статусы постов "Прочитан"',
            },
        ),
        migrations.AddConstraint(
            model_name='isread',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_is_read'),
        ),
    ]
