# Generated by Django 4.2.9 on 2024-02-05 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_read', to='posts.post', verbose_name='Пост прочитан/не прочитан')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_read', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статус поста "Прочитан"',
                'verbose_name_plural': 'Статусы постов "Прочитан"',
            },
        ),
        migrations.AddConstraint(
            model_name='isread',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_is_read'),
        ),
    ]
